= Dokumentacja projektu doc-digit
Rafal Aspras, Mateusz Koczan
v0.01, 2018-11-19
:example-caption!:
ifndef::imagesdir[:imagesdir: images]

== Technologie

. Client - C#
* WPF
* Twain

. Server - Java
* Hibernate
* Tesseract

. API - Python
* Django REST Framework

. Storage
* Minio

. Database
* Postgres

. Documentation
* Asciidoctor
* Mermaid

. Testing
* JUnit
* CircleCi

== Model uprawnień do zasobów

* Admin: all
* Client: Wysyła pliki, dostęp do wszystkich plików
* Student: Dostęp do swoich oraz publicznych plików

<<<
== Diagramy

* Wysłanie pliku do przetworzenia

[mermaid, config="asc.conf", align="center"]
....
graph TB
A[fa:fa-desktop Client] -->|1.Get file| B(fa:fa-archive Storage)
B -->|2.Get key to file| A
A -->|3.Set loading screen :|G[fa:fa-spinner]
B -->|4. Invoke|C[fa:fa-file API]
C --> |5. Add record|D[fa:fa-database DB]
C --> |6. Run for processing|E[fa:fa-server Server]
E -->|7.Send key for file| B
B -->|8.File to process|E

....

* Powrót do klienta po przetworzeniu

[mermaid, config="asc.conf", align="center"]
....
graph BT
C[fa:fa-file API] -.-> G
E[fa:fa-server Server] --> |1.Change status|D[fa:fa-database DB]
E -.-> C
E -->|2.Send processed file ::|B(fa:fa-archive Storage)
G[fa:fa-spinner] -.-> A[fa:fa-desktop Client] 

....

* Zapisanie sesji skanowania

[mermaid, config="asc.conf", align="center"]
....
graph TB
A[fa:fa-desktop Client] -->|1.Send pages for conversion|C(fa:fa-file API)
C --> |2.Change status|D[fa:fa-database DB]
C --> |3.Run for conversion into PDF|E[fa:fa-server Server]
D -->|4.Get status|E
E -->|5.Converting into PDF :|E
....

* Po zrobieniu pdfa

[mermaid, config="asc.conf", align="center"]
....
graph BT
E[fa:fa-server Server] --> |1.Edit record|D[fa:fa-database DB]
E --> |2. Send file|B[fa:fa-archive Storage]
....

== Architektura

[mermaid, config="asc.conf", align="center"]
....
graph TB
A[fa:fa-desktop Client] --- B(fa:fa-archive Storage)
F[fa:fa-user ISOD] --- B
B --- C[fa:fa-file API]
A --- C
F --- C
B --- E
C --- E
C --- D[fa:fa-database DB]
D --- E[fa:fa-server Server]
....
